chore: update
Signed-off-by: Charles Chin <eallion.s+github@gmail.com>

diff --git a/.github/workflows/build-x86-64-24.10.2.yml b/.github/workflows/build-x86-64-24.10.2.yml
--- a/.github/workflows/build-x86-64-24.10.2.yml
+++ b/.github/workflows/build-x86-64-24.10.2.yml
@@ -13,7 +13,7 @@ on:
         description: |
           是否编译 Docker 插件
         required: true
-        default: 'yes'
+        default: 'no'
         type: choice
         options:
           - 'yes'
@@ -79,51 +79,51 @@ jobs:
           fi
 
 
-      - name: Download custom IPK files
-        id: download-ipk
-        run: |
-          # 创建目录
-          mkdir -p custom_pkgs
-
-          # 定义仓库和文件匹配规则
-          REPO="QiuSimons/luci-app-daed"
-          FILE_PATTERNS=(
-            "daed_.*_x86_64.ipk"
-            "luci-app-daed_.*_all.ipk"
-            "luci-i18n-daed-zh-cn_.*_all.ipk"
-          )
-
-          # 获取最新 Release 的资产列表
-          RELEASE_API_URL="https://api.github.com/repos/$REPO/releases/latest"
-          ASSETS=$(curl -sSL "$RELEASE_API_URL" | jq -r '.assets[].browser_download_url')
-
-          if [ -z "$ASSETS" ]; then
-            echo "::error::Failed to fetch release assets"
-            exit 1
-          fi
-
-          # 下载匹配的文件
-          DOWNLOADED=0
-          for pattern in "${FILE_PATTERNS[@]}"; do
-            file_url=$(echo "$ASSETS" | grep -E "$pattern" | head -1)
-            if [ -n "$file_url" ]; then
-              echo "Downloading: $file_url"
-              # 静默下载（不显示进度）
-              wget -q -O "custom_pkgs/$(basename "$file_url")" "$file_url"
-              if [ $? -eq 0 ]; then
-                DOWNLOADED=$((DOWNLOADED + 1))
-              else
-                echo "::error::Failed to download $file_url"
-                exit 1
-              fi
-            fi
-          done
-
-          # 验证是否下载全部文件
-          if [ $DOWNLOADED -ne 3 ]; then
-            echo "::error::Missing required IPK files"
-            exit 1
-          fi
+#       - name: Download custom IPK files
+#         id: download-ipk
+#         run: |
+#           # 创建目录
+#           mkdir -p custom_pkgs
+# 
+#           # 定义仓库和文件匹配规则
+#           REPO="QiuSimons/luci-app-daed"
+#           FILE_PATTERNS=(
+#             "daed_.*_x86_64.ipk"
+#             "luci-app-daed_.*_all.ipk"
+#             "luci-i18n-daed-zh-cn_.*_all.ipk"
+#           )
+# 
+#           # 获取最新 Release 的资产列表
+#           RELEASE_API_URL="https://api.github.com/repos/$REPO/releases/latest"
+#           ASSETS=$(curl -sSL "$RELEASE_API_URL" | jq -r '.assets[].browser_download_url')
+# 
+#           if [ -z "$ASSETS" ]; then
+#             echo "::error::Failed to fetch release assets"
+#             exit 1
+#           fi
+# 
+#           # 下载匹配的文件
+#           DOWNLOADED=0
+#           for pattern in "${FILE_PATTERNS[@]}"; do
+#             file_url=$(echo "$ASSETS" | grep -E "$pattern" | head -1)
+#             if [ -n "$file_url" ]; then
+#               echo "Downloading: $file_url"
+#               # 静默下载（不显示进度）
+#               wget -q -O "custom_pkgs/$(basename "$file_url")" "$file_url"
+#               if [ $? -eq 0 ]; then
+#                 DOWNLOADED=$((DOWNLOADED + 1))
+#               else
+#                 echo "::error::Failed to download $file_url"
+#                 exit 1
+#               fi
+#             fi
+#           done
+# 
+#           # 验证是否下载全部文件
+#           if [ $DOWNLOADED -ne 3 ]; then
+#             echo "::error::Missing required IPK files"
+#             exit 1
+#           fi
 
       - name: Build ImmortalWrt-x86-64-EFI
         run: |
@@ -144,7 +144,6 @@ jobs:
               -v "${{ github.workspace }}/files:/home/build/immortalwrt/files" \
               -v "${{ github.workspace }}/x86-64/immortalwrt.config:/home/build/immortalwrt/.config" \
               -v "${{ github.workspace }}/x86-64/build.sh:/home/build/immortalwrt/build.sh" \
-              -v "${{ github.workspace }}/custom_pkgs:/home/build/immortalwrt/packages/custom" \
               -e PROFILE=$profile \
               -e INCLUDE_DOCKER=$include_docker \
               -e ENABLE_PPPOE=$enable_pppoe \
@@ -175,7 +174,7 @@ jobs:
           echo -e "| Image | ⬇️ [immortalwrt-x86-64-generic-squashfs-combined-efi.img.gz](https://github.com/eallion/openwrt/releases/download/"$RELEASE_TAG"/immortalwrt-x86-64-generic-squashfs-combined-efi.img.gz) |" >> release.txt
           echo -e "| Date | `date +"%H:%M %a, %b %d, %Y"` |" >> release.txt
           echo -e "| Source | [https://github.com/immortalwrt/immortalwrt](https://github.com/immortalwrt/immortalwrt) |" >> release.txt
-          echo -e "| Branch | openwrt-24.10.2 |" >> release.txt
+          echo -e "| Branch | openwrt-24.10 |" >> release.txt
           echo -e "| Architecture | x86-64 |" >> release.txt
           echo -e "| FS | squashfs |" >> release.txt
           echo -e "| FI | EFI |" >> release.txt
